<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title', 'Report')</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Inter', sans-serif; -webkit-print-color-adjust: exact; print-color-adjust: exact; background-color: #f9fafb;}
        .report-page { max-width: 210mm; min-height: 297mm; margin: 20px auto; padding: 20mm; background: white; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        .theme-text { color: #0077b6; }
        .theme-bg { background-color: #0077b6; color: white; }
        @media print {
            body { background-color: white; margin: 0; padding: 0; }
            .report-page { box-shadow: none; margin: 0; width: 100%; max-width: none; padding: 0; }
            @page { margin: 15mm; }
        }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; font-size: 14px; }
        th { background-color: #f3f4f6; font-weight: bold; color: #374151; }
    </style>
</head>
<body onload="window.print();">
    <div class="report-page">
        <!-- Header -->
        <div class="flex justify-between items-end border-b-2 border-gray-200 pb-6 mb-6">
            <div>
                <h1 class="text-3xl font-extrabold text-gray-800">Ibtisama Clinic</h1>
                <p class="text-sm text-gray-500 mt-1">Dental Clinic & Pharmacy</p>
                <p class="text-sm text-gray-500">123 Health Ave, Medical District</p>
                <p class="text-sm text-gray-500">Phone: (123) 456-7890</p>
            </div>
            <div class="text-right">
                <h2 class="text-2xl font-bold theme-text uppercase tracking-wider mb-2">@yield('title')</h2>
                <div class="text-sm text-gray-600 font-semibold mb-1">
                    Date: <span class="text-gray-800">{{ now()->format('M d, Y H:i') }}</span>
                </div>
                <div class="text-sm text-gray-600 font-semibold mb-1">
                    Generated By: <span class="text-gray-800">{{ auth()->user()->name ?? 'System' }}</span>
                </div>
            </div>
        </div>

        <!-- Content -->
        <div class="report-content">
            @yield('content')
        </div>

        <!-- Footer -->
        <div class="mt-16 text-center text-xs text-gray-400 border-t border-gray-100 pt-4">
            <p>End of Report</p>
            <p class="mt-2 font-mono text-[10px]">Ibtisama Clinic System</p>
        </div>
    </div>
</body>
</html>
