<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title', 'Receipt')</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&display=swap');
        
        body {
            font-family: 'Courier Prime', 'Courier New', Courier, monospace;
            margin: 0;
            padding: 0;
            background-color: #f3f4f6;
            color: #000;
            font-size: 12px;
            display: flex;
            justify-content: center;
        }
        .receipt-container {
            background-color: #fff;
            padding: 5mm;
            width: 80mm;
            min-height: 100vh;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-left { text-align: left; }
        .font-bold { font-weight: bold; }
        .divider { border-bottom: 1px dashed #000; margin: 8px 0; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 4px 0; }
        th { border-bottom: 1px dashed #000; text-align: left; }
        .item-name { display: block; font-size: 11px; max-width: 40mm; word-wrap: break-word; font-weight: bold;}
        
        @media print {
            body { 
                width: 80mm; 
                background-color: #fff;
                display: block;
            }
            .receipt-container { 
                padding: 0; 
                margin: 0; 
                width: 100%; 
                box-shadow: none;
                min-height: auto;
            }
            @page { margin: 0; }
        }
    </style>
</head>
<body onload="window.print();">
    <div class="receipt-container">
        <!-- Header -->
        <div class="text-center">
            <h2 style="margin: 0; font-size: 18px; font-weight: bold;">@yield('receipt_title', 'IBTISAMA CLINIC')</h2>
            <p style="margin: 3px 0; font-size: 11px;">@yield('receipt_subtitle', 'Dental Clinic & Pharmacy')</p>
            <p style="margin: 3px 0; font-size: 11px;">123 Health Ave, Medical District</p>
            <p style="margin: 3px 0; font-size: 11px;">Tel: (123) 456-7890</p>
        </div>
        
        <div class="divider" style="margin-top: 12px;"></div>
        
        <!-- Content -->
        @yield('content')
        
        <!-- Footer -->
        <div class="divider" style="margin-bottom: 12px;"></div>

        <div class="text-center" style="font-size: 11px;">
            <p style="margin: 4px 0; font-weight: bold;">*** THANK YOU ***</p>
            <p style="margin: 4px 0;">Please keep this receipt</p>
            <p style="margin: 4px 0; font-size: 9px; color: #666;">Generated by Ibtisama System</p>
        </div>
    </div>
</body>
</html>
